### ISSUE TITLE
Min impurity decrease

### ISSUE THREAD

**Issue by pspachtholz** [cerlymarco/linear-tree#11]
Hi, I really like your linear-tree library. I have been looking for something like this a while and it perfectly fits my use case.
If I understand the LinearTreeRegressor correctly a node is split when the weighted loss of the child nodes is less than the loss of the parent node. 

What I would like to do is to only split a node if the decrease in loss is over a certain threshold. Scikit-learn has something called min_impurity_decrease which could be used.

I implemented a small suggestion in a PR. So I would be happy to expand on this and improve it (e.g. input validation, maybe extend to classification), if you find that useful.

**Comment by cerlymarco** [comment]
Hi, thanks for your feedback. It seems reasonable... I'll give a look at the PR in the next days.

If you support the project don't forget to leave a star ;-)
