### ISSUE TITLE
ValueError: Invalid parameter linearforestregression for estimator Pipeline

### ISSUE THREAD

**Issue by QiaomeiFeng** [cerlymarco/linear-tree#15]
Great work! I'm new to ML and stuck with this. 
I'm trying to combine pipeline and GridSearch to search for best possible hyperparameters for a model.

![image](https://user-images.githubusercontent.com/84954535/150624770-497aa9e3-24dc-4745-b529-9897ade81801.png)

I got the following error:

![image](https://user-images.githubusercontent.com/84954535/150624801-39f09d2b-e3e3-4ef6-ac65-6a496745ff5f.png)

Kindly help : )

**Comment by cerlymarco** [comment]
Hi,

it's `linearforestregressor__n_estimators `not `linearforestregression__n_estimators `

All the best

**Comment by QiaomeiFeng** [comment]
Oh, I made a stupid mistake. Thank you for your time.
