### ISSUE TITLE
learning_rate in boosting

### ISSUE THREAD

**Issue by fipelle** [cerlymarco/linear-tree#17]
Hi, is there a way for setting the `learning_rate` in the boosting regressors and classifiers?

EDIT:
Also, is LinearBoostingRegressor fitting a linear regression first and then boosting the residual via regression trees or boosting via a series of linear regression trees?

**Comment by cerlymarco** [comment]
Hi, thanks for your feedback.

No, here `learning_rate` is not involved.

_Linear Boosting is a two-stage learning process. Firstly, a linear model is trained on the initial dataset to obtain predictions. Secondly, the residuals of the previous step are modeled with a decision tree using all the available features. The tree identifies the path leading to the highest error (i.e. the worst leaf). The leaf contributing to the error the most is used to generate a new binary feature to be used in the first stage._ 

In this sense, I think the [code](https://github.com/cerlymarco/linear-tree/blob/e07c2d485018ba0bb3defa81e3941b1b921faa49/lineartree/_classes.py#L907-L948) is quite explicative.

If you support the project don't forget to leave a star ;-)
