### ISSUE TITLE
Linear Boosting will it work for categorical features? 

### ISSUE THREAD

**Issue by Sandy4321** [cerlymarco/linear-tree#27]
Linear Boosting will it work for categorical features?

**Comment by cerlymarco** [comment]
Hi, 

ALL the estimators in linear-tree are sklearn estiamtors. They don't automatically encode categorical features. You should use your own strategy for categorical features encoding

If you support support the project, don't forget to leave a star ;-)

**Comment by Sandy4321** [comment]
Star done

**Comment by Sandy4321** [comment]
Do you have examples 
When your code is much better than gxboost?
Do you planning to add your linear regression splits to gradient busting?
Seems to be some of gbm packages already has  linear regression splits?
