### ISSUE TITLE
numpy deprecation warning

### ISSUE THREAD

**Issue by paul-brenner** [cerlymarco/linear-tree#28]
/lineartree/_classes.py:338: DeprecationWarning:

the `interpolation=` argument to quantile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)

Seems like a quick update [here](https://github.com/cerlymarco/linear-tree/blob/6b76c6140eec9271211b254cf0a89283a684d960/lineartree/_classes.py#L338) would get this warning to stop showing up, right? I can always ignore it, but figured I would mention it in case it is actually an error on my side. 

Also, sorry, I don't actually what the best open source etiquette is. If I'm supposed to create a pull request with a proposed fix instead of just mentioning it then feel free to correct me.

**Comment by cerlymarco** [comment]
Hi, thanks for this catch!

I decided to use the standard linear interpolation/method when computing quantile. This is the same strategy applied in sklearn [KBinsDiscretizer](https://github.com/scikit-learn/scikit-learn/blob/36958fb240fbe435673a9e3c52e769f01f36bec0/sklearn/preprocessing/_discretization.py#L269) for computing quantiles.

If you support the project, don't forget to leave a star ;-)
