### ISSUE TITLE
Non coherent splitting results

### ISSUE THREAD

**Issue by AIProgrammerFan** [cerlymarco/linear-tree#34]
Hello,
I have a dataframe with a column X >= 0. I added its index in the parameter split_features of LinearTreeRegressor.
I set max_depth to 1 and then used LinearRegression() as a base estimator.
When I count the number of samples at node_1 i.e. assumed to be <= to the indicated threshold (from the node_0) I realize that it doesn't correspond to my data for the column X.
When I increase max_depth some negative splitting thresholds appear whereas the column X is >= 0 as said previously.
do you normalize data or scale it somehow before training?
Thanks in advance !

**Comment by cerlymarco** [comment]
Hi, 
no normalization/scaling is applied during fitting. 
could u please provide a reproducible example of the error?
Thanks

If u support the project don't forget to leave a star ;-)

**Comment by AIProgrammerFan** [comment]
Thank you for your prompt feedback.
Actually, the scaling was activated by default in a class belonging to my project. Sorry about that.
