### ISSUE TITLE
Have precision of threshold be customizable

### ISSUE THREAD

**Issue by dawidjaja** [cerlymarco/linear-tree#35]
Currently, we hard code the precision of threshold as 5 in [here](https://github.com/cerlymarco/linear-tree/blob/2982edc050206521fa9cde7df1b1f88ab7b2183d/lineartree/_classes.py#L656). Having this customizable will allow us to use the linear tree model when the number that are used are smaller in general. My suggestion is have another parameter that defaults to 5 and when people wants to use the model with smaller number, they could do it by set this parameter to the number they desired. 

Let me know if this change is good and I could create a PR for it. I'm open for discussion.

**Comment by cerlymarco** [comment]
Hi, 
the code reference you are pointing out is for "visualization" purposes. In other words, when you call the `summary` or `model_to_dot` methods the threshold values are rounded to 5 digits. This does not influence the training behavior as you see ([here](https://github.com/cerlymarco/linear-tree/blob/2982edc050206521fa9cde7df1b1f88ab7b2183d/lineartree/_classes.py#L413), [here](https://github.com/cerlymarco/linear-tree/blob/2982edc050206521fa9cde7df1b1f88ab7b2183d/lineartree/_classes.py#L424) and [here](https://github.com/cerlymarco/linear-tree/blob/2982edc050206521fa9cde7df1b1f88ab7b2183d/lineartree/_classes.py#L443)).
If u support the project, don't forget to leave a star ;-)

**Comment by dawidjaja** [comment]
Hi @cerlymarco,
I'm trying to get the tree details (threshold, loss, children) and use it elsewhere. it seems that I shouldn't use `self._nodes` directly as it seems that you intend it to be a private member. How about adding another API to return the _nodes so that there's a way to get these information with complete precision?

**Comment by dawidjaja** [comment]
@cerlymarco hello, is there any solution for this?

**Comment by cerlymarco** [comment]
@dawidjaja 

`self._nodes` is not a private method

<img width="305" alt="image" src="https://github.com/cerlymarco/linear-tree/assets/36955807/062a57e4-2060-46a9-9379-e0d78fc5ea5e">
