### ISSUE TITLE
Maximum Slope limiter 

### ISSUE THREAD

**Issue by nurrochmanmuhammad** [cerlymarco/linear-tree#39]
Hi @cerlymarco , thanks for developing this method into a good library.

Im thinking , maybe for some cases / most cases we need maximum slope for each regressor. The main concept is to prevent over optimistic extrapolation for prediction output.

If slope > max slope , then split that into a new node.

**Comment by cerlymarco** [comment]
Hi, thanks for your feedback!

Feel free to submit a pull request with your idea

If you support the project, don't forget to leave a star ;-)
