### ISSUE TITLE
What about spline-tree?

### ISSUE THREAD

**Issue by BiaPri** [cerlymarco/linear-tree#42]
Hi cerlymarco,

As always, nice work! What do you think about the idea of adding splines in the leaves?

I will investigate that soon, but I was wondering what were your thoughts on the topic.

Grazie mille,

B.

**Comment by cerlymarco** [comment]
Hi,
this will be an interesting idea! 
feel free to share some materials or contribute
Thanks

**Comment by cerlymarco** [comment]
Closed due to inactivity
