### ISSUE TITLE
Why LinearForestRegressor model returns almost constant prediction?

### ISSUE THREAD

**Issue by clevilll** [cerlymarco/linear-tree#43]
Hi,
I was exploring in-sample forecasting of **skforecast** package. I'm using cloud data with a frequency of 5mins (epoch=5mins). I have used `RandomForestRegressor` besides `LinearForestRegressor` from **linear-tree** package based on the recommendation of @JoaquinAmatRodrigo  in this [issue](https://github.com/skforecast/skforecast/issues/488#issuecomment-1595188283). I don't know why with my current setup performance of the RF and LF models are saturated and return to **almost constant** values and it can't capture the dynamic data. Both regressors performed weak (specifically LF) and I could not find a solution so far from its documentation to see what are the potential hyper-parameters. 
```python
#-----------------------------------------------------------
# Train RandomForestRegressor
#-----------------------------------------------------------
rf_forecaster = ForecasterAutoreg(
    regressor=RandomForestRegressor(random_state=42, n_jobs=-1),
    lags=288
)
rf_forecaster.fit(y=train)
rf_predictions = rf_forecaster.predict(steps=len(test))

#-----------------------------------------------------------
# Train LinearForestRegressor
#-----------------------------------------------------------

lf_forecaster = LinearForestRegressor(
    base_estimator=Ridge(random_state=42), 
    n_estimators=50, 
    n_jobs=-1,
    # Explicitly set max_features to a valid value, e.g., 'sqrt'
    max_features='sqrt'  
) 
lf_forecaster.fit(np.arange(len(train)).reshape(-1, 1), train.values)

lf_predictions = lf_forecaster.predict(np.arange(len(train), len(train) + len(test)).reshape(-1, 1))
```
The following is used configurations and dependencies:
```none
Number of CPUs available: 2
-----
lineartree          NA
matplotlib          3.8.0
numpy               1.26.4
pandas              2.2.2
session_info        1.0.0
skforecast          0.13.0
sklearn             1.5.2
-----
IPython             7.34.0
jupyter_client      6.1.12
jupyter_core        5.7.2
notebook            6.5.5
-----
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
Linux-6.1.85+-x86_64-with-glibc2.35
-----
Session information updated at 2024-11-17 07:35
Mean Squared Error (RandomForestRegressor): 0.0077
Mean Squared Error (LinearForestRegressor): 0.0146
```
---
This is the output forecast results:
![image](https://github.com/user-attachments/assets/130eaedc-9de8-4b2b-b43a-c5552dbc07a1)

Please let me know **what the best setup** for the LF model is if there is a chance to use it within `ForecasterAutoreg()` with better performance to follow the **dynamic of data** within **skforecast** package. 
**Side note:** I'm aware of `GridSearchCV()` but it seems learning or generalization gets over\under-fitted and after a while, it returns almost constant values.

**Comment by cerlymarco** [comment]
Hi, 
**LinearForestRegressor is not an autoregressive model**. It fit a linear regression on your data and then a random forest on the resiaduals using the same features. As a feature, you are using a simple straight-line so the model can't do magic. Maybe you can try to use LinearForestRegressor as a regressor of ForecasterAutoreg.
If you support the project don't forget to leave a star.
All the best ;-)

**Comment by clevilll** [comment]
@cerlymarco thanks for your reply I have tried `LinearTreeRegressor` but have not had a comparable result!
![image](https://github.com/user-attachments/assets/3013cba6-a507-4a97-b8c4-c732049999ee)

What are the best use cases of the models within the package `lineartree` proposed? It does not have something interesting for Forecasting over uni-variate time data! (at least on highly frequent ones if we can call it (epochs=5mins))
I will support your Repo for sure.

**Comment by JoaquinAmatRodrigo** [comment]
Hi @clevilll,
As @cerlymarco mentioned, you may benefit from using `LinearForestRegressor` for forecasting by combining it with a `ForecasterRecursive`.

```python
regressor = LinearForestRegressor(base_estimator=LinearRegression(), random_state=963, max_features='sqrt')
forecaster_linear_forest = ForecasterRecursive(
                                            regressor = regressor,
                                            lags      = 12  # Set here the appropriate lags for your use case.
                                       )
```

**Comment by clevilll** [comment]
@JoaquinAmatRodrigo Thanks for your input. I have tried it successfully.
```python
#!pip install skforecast==0.14.0
from skforecast.recursive import ForecasterRecursive
```
instead of :
```python
# !pip install skforecast==0.13.0
from skforecast.ForecasterAutoreg import ForecasterAutoreg 
```
I did not know about this update due to the new release: [Changes in the import of the library](https://skforecast.org/0.14.0/user_guides/migration-guide#changes-in-the-import-of-the-library)
![image](https://github.com/user-attachments/assets/d4e9ff0b-9aed-4d1e-bd99-9fbe5a10624c)
