### ISSUE TITLE
Extract Coefficients

### ISSUE THREAD

**Issue by YorgosMoiragias** [cerlymarco/linear-tree#5]
How can someone extract the coefficients of each linear model implemented in each leaf?

**Comment by unnamed-idea** [comment]
hello, your link does not include the code to get the coefficients of the each of the leaf estimators (eg linear regression). Can you elaborate on this subject?

**Comment by cerlymarco** [comment]
At the bottom of the post, click to "CHECK MY GITHUB REPOSITORY". 

The notebook you are interested in is: https://github.com/cerlymarco/MEDIUM_NoteBook/tree/master/ModelTrees_Explainability

If you support the project don't forget to leave a star ;-)
