### ISSUE TITLE
AttributeError: 'LinearTreeRegressor' object has no attribute '_validate_data'

### ISSUE THREAD

**Issue by ShrinathVis** [cerlymarco/linear-tree#7]
Got this error when trying to follow examples to train model

**Comment by cerlymarco** [comment]
You simply need to update your sklearn to Version 0.23 or higher

This is specified in the requirements.txt: https://github.com/cerlymarco/linear-tree/blob/e47bd01afaad3c2f67432b5f853e51dc67a9884a/requirements.txt#L3

If you support the project don't forget to leave a star ;-)

**Comment by NorwegianGoat** [comment]
Hi, I'm writing this comment just to say that I encountered this same error, but I have scikit-learn 1.7.2 installed.
