### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by YorgosMoiragias** [cerlymarco/linear-tree#9]
Hi,

I really like your work with Linear Trees, I would like to ask if there are references in some kind of papers, which describe accurately in the form of equations  the split procedure!!

Thank you in advance,
George Moiragias

**Comment by cerlymarco** [comment]
Hi, thanks for your feedback

As a base reference you can consider these works:

Ross J. Quinlan: Learning with Continuous Classes. In: 5th Australian Joint Conference on Artificial Intelligence, Singapore, 343-348, 1992.

Y. Wang, I. H. Witten: Induction of model trees for predicting continuous classes. In: Poster papers of the 9th European Conference on Machine Learning, 1997.

However, the way linear trees are developed here is simpler than expected. The logic of splitting is based simply on evaluating the loss of candidate children after fitting linear models on the splits. If you know how decision trees work it is straightforward to adopt the same concept to linear trees. The core function to evaluate the splits in my code is present [here](https://github.com/cerlymarco/linear-tree/blob/e47bd01afaad3c2f67432b5f853e51dc67a9884a/lineartree/_classes.py#L78)

Thanks
